
all:
	g++ src/ou5.cpp src/shape.cpp src/point.cpp src/vertex.cpp src/circle.cpp src/rectangle.cpp src/polygon.cpp src/shapeptr.cpp -o bin/ou5 -g -Wall
clean:
	rm -rf bin/ou5
































