
all:
	g++ src/ou4.cpp src/media.cpp src/book.cpp src/journal.cpp src/cd.cpp src/fiction.cpp src/noneFiction.cpp src/helper.cpp src/regHandler.cpp -o bin/ou4 -std=c++11 -g -Wall
clean:
	rm -rf bin/ou4
































