
all:
	g++ src/ou3.cpp src/shape.cpp src/point.cpp src/vertex.cpp src/shapelist.cpp src/circle.cpp src/rectangle.cpp src/polygon.cpp -o bin/ou3 -g -Wall
clean:
	rm -rf bin/ou3
































